name: "Grocy (Latest)"
version: "1.0.0"
slug: "grocy_latest"
description: "Grocy avec image Docker à jour"
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  9283/tcp: 9283
map:
  - addon_config:rw
options: {}
schema: {}
ingress: true
ingress_port: 9283
panel_title: Grocy
panel_icon: mdi:fridge-outline
