name: "Grocy"
version: "4.6.0.11"
slug: "grocy_latest"
description: "Grocy 4.6.0 - ERP beyond your fridge"
url: "https://github.com/grocy/grocy"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
webui: "http://[HOST]:[PORT:9283]"
ports:
  9283/tcp: 9283
map:
  - config:rw
