name: "Grocy (Latest)"
slug: "grocy_latest"
version: "1.0.1"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false

ingress: true
ingress_port: 9283
panel_icon: mdi:fridge-outline
panel_title: Grocy
